# Generated by Django 3.2.4 on 2021-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='author_picture',
            field=models.ImageField(default='', upload_to='author_pictures/'),
            preserve_default=False,
        ),
    ]
