# Generated by Django 3.2.4 on 2021-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210626_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='WebSite'),
        ),
    ]
